language: c
compiler: clang

# Asterisk-11
before_script:
 - autoreconf -fi
before_install:
 - sudo apt-add-repository -y ppa:d-shegolihin/asterisk
# - sudo apt-add-repository -y ppa:blackz/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq asterisk-11.2.1

# Asterisk-1.8
#before_script:
# - autoreconf -fi
#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq asterisk- asterisk-dev asterisk-config

notifications:
  email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net
