language: c
compiler: clang

# Asterisk-11
before_script:
 - autoreconf -fi

before_install:
# - sudo apt-add-repository -y ppa:d-shegolihin/asterisk
 - echo "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"            | sudo tee -a /etc/apt/sources.list.d/trusty.list
 - echo "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"    | sudo tee -a /etc/apt/sources.list.d/trusty.list
 - echo "deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/trusty.list
 - echo "deb http://archive.canonical.com/ubuntu/ trusty partner"                                    | sudo tee -a /etc/apt/sources.list.d/trusty.list
 - sudo apt-get update -qq
# - sudo apt-get install -qq asterisk-11.2.1
 - sudo apt-get install -qq asterisk asterisk-dev asterisk-config asterisk-modules

notifications:
  email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net
