language: c

# Setup Build Matrix
compiler: 
 - gcc

env:
  global:
    secure: "JDdGOmj9jw2-oYEssxTABw"

branch_pattern: coverity_scan

# Install Required Devel Packages
before_install:
  if test 1 -eq 1: then
    echo "deb http://archive.ubuntu.com/ubuntu ${REPO} main restricted universe multiverse"            | sudo tee -a /etc/apt/sources.list.d/trusty.list;
    echo "deb http://archive.ubuntu.com/ubuntu ${REPO}-updates main restricted universe multiverse"    | sudo tee -a /etc/apt/sources.list.d/trusty.list;
    echo "deb http://security.ubuntu.com/ubuntu/ ${REPO}-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/trusty.list;
    echo "deb http://archive.canonical.com/ubuntu/ ${REPO} partner"                                    | sudo tee -a /etc/apt/sources.list.d/trusty.list;
    sudo apt-get update -qq;
    sudo apt-get install -qq asterisk asterisk-dev asterisk-config asterisk-modules binutils.dev libc6-dev;
  fi

before_script: autoreconf -fi

build_command_prepend: ./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-devdoc --enable-advanced-functions

build_command: make

notifications:
 slack: chan-sccp:yfQzKYTnTf4cD1iHElnTYsXD
 email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net

addons:
  coverity_scan:
    project:
      name: dkgroot/chan-sccp-b
      version: 4.3
      description: Asterisk SCCP Channel
